### ISSUE TITLE
Modular UI design

### ISSUE THREAD

**Issue by aminations** [build-a-thing-and-show/login-service#17]
Refactor the UI so it's more modular.

**Comment by rzgholizadeh** [comment]
This is applicable to core-ui now.

**Comment by rzgholizadeh** [comment]
This is the PR:
https://github.com/build-a-thing-and-show/core-ui/pull/3

**Comment by rzgholizadeh** [comment]
PR is merged and app is running.
@aminations  please review at your convenience so we can close the issue.
