### ISSUE TITLE
Add UI components to the project

### ISSUE THREAD

**Issue by rzgholizadeh** [build-a-thing-and-show/login-service#5]
**DOD:**

-  We have a basic UI for the website.
-  The first version have a login window and lands in a basic landing page with a welcome

**Comment by aminations** [comment]
Sub tasks:

- Create a landing page with the logo and the colour
- Create a DB for saving users and passwords.

**Comment by rzgholizadeh** [comment]
It seems that requires a separate issue. Since this one is only for the UI component. Not the login functionality.

**Comment by aminations** [comment]
Makes sense. I created another issue for that (issue #11 )

**Comment by rzgholizadeh** [comment]
Review completed
